/**
 * Get word-level timestamps for all scenes.
 * Reads from .words.json files generated by the voiceover module.
 */
import { getWordTimestamps } from './voiceover.js';

export function transcribeAllScenes(audioPaths) {
  const results = [];
  for (let i = 0; i < audioPaths.length; i++) {
    const words = getWordTimestamps(audioPaths[i]);
    if (words) {
      console.log(`  ✓ Word sync scene ${i + 1}/${audioPaths.length} (${words.length} words)`);
    } else {
      console.log(`  ~ Scene ${i + 1}: proportional fallback`);
    }
    results.push(words);
  }
  return results;
}
